# Generated by Django 4.2.8 on 2023-12-23 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ezziee.utils.files
import ezziee.utils.validators
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardRequests",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.FileField(
                        upload_to=ezziee.utils.files.FileUploader.profile_image_upload_path,
                        validators=[ezziee.utils.validators.image_validate_file_extension],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("description", models.TextField()),
                ("expiry", models.DateField(blank=True, null=True)),
                ("fb_share_url", models.CharField(blank=True, max_length=500, null=True)),
                ("fb_like_url", models.CharField(blank=True, max_length=500, null=True)),
                ("fb_comment_url", models.CharField(blank=True, max_length=500, null=True)),
                ("fb_follow_url", models.CharField(blank=True, max_length=500, null=True)),
                ("fb_post_id", models.CharField(blank=True, max_length=500, null=True)),
                ("ig_artist_username", models.CharField(blank=True, max_length=500, null=True)),
                ("ig_artist_id", models.CharField(blank=True, max_length=500, null=True)),
                ("ig_post_id", models.CharField(blank=True, max_length=500, null=True)),
                ("spotify_artist_id", models.CharField(blank=True, max_length=500, null=True)),
                ("spotify_playlist_id", models.CharField(blank=True, max_length=500, null=True)),
                ("spotify_album_id", models.CharField(blank=True, max_length=500, null=True)),
                ("spotify_track_id", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="RewardActions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("COMMENTS", "COMMENTS"), ("LIKES", "LIKES"), ("FOLLOWING", "FOLLOWING")],
                        default="COMMENTS",
                        max_length=25,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("FACEBOOK", "FACEBOOK"),
                            ("INSTAGRAM", "INSTAGRAM"),
                            ("SOUNDCLOUD", "SOUNDCLOUD"),
                            ("TWITTER", "TWITTER"),
                            ("SPOTIFY", "SPOTIFY"),
                        ],
                        default="FACEBOOK",
                        max_length=25,
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="rewards.rewardrequests",
                    ),
                ),
                (
                    "subscribers",
                    models.ManyToManyField(
                        related_name="actions", to=settings.AUTH_USER_MODEL, verbose_name="subscribers"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward Action",
                "verbose_name_plural": "Rewards Actions",
                "ordering": ["-modified"],
            },
        ),
    ]
