# Generated by Django 4.2.8 on 2023-12-25 08:39

from django.db import migrations, models
import ezziee.utils.files
import ezziee.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("rewards", "0002_rewardrequests_youtube_channel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardrequests",
            name="image",
            field=models.FileField(
                upload_to=ezziee.utils.files.FileUploader.profile_image_upload_path,
                validators=[ezziee.utils.validators.image_validate_file_extension],
            ),
        ),
    ]
