# Generated by Django 4.2.8 on 2023-12-25 20:56

from django.db import migrations, models
import ezziee.utils.files
import ezziee.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("rewards", "0004_alter_rewardrequests_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardrequests",
            name="max_users",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="rewardrequests",
            name="image",
            field=models.FileField(
                upload_to=ezziee.utils.files.FileUploader.profile_image_upload_path,
                validators=[ezziee.utils.validators.image_validate_file_extension],
            ),
        ),
    ]
