# Generated by Django 4.2.8 on 2023-12-25 21:08

from django.conf import settings
from django.db import migrations, models
import ezziee.utils.files
import ezziee.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rewards", "0005_rewardrequests_max_users_alter_rewardrequests_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rewardactions",
            name="subscribers",
        ),
        migrations.AddField(
            model_name="rewardrequests",
            name="paying",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="rewardrequests",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="requests", to=settings.AUTH_USER_MODEL, verbose_name="subscribers"
            ),
        ),
        migrations.AlterField(
            model_name="rewardrequests",
            name="image",
            field=models.FileField(
                upload_to=ezziee.utils.files.FileUploader.profile_image_upload_path,
                validators=[ezziee.utils.validators.image_validate_file_extension],
            ),
        ),
    ]
