# Generated by Django 4.2.8 on 2024-01-15 15:36

from django.db import migrations, models
import ezziee.utils.files
import ezziee.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("rewards", "0011_alter_rewardrequests_image_completedactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardactions",
            name="endpoint",
            field=models.CharField(
                choices=[
                    ("LIKE_POST", "LIKE_POST"),
                    ("FOLLOW_ARTIST", "FOLLOW_ARTIST"),
                    ("FOLLOW_PLAYLIST", "FOLLOW_PLAYLIST"),
                    ("SAVE_ALBUM", "SAVE_ALBUM"),
                    ("SAVE_TRACK", "SAVE_TRACK"),
                    ("SHARE_POST", "SHARE_POST"),
                ],
                default="LIKE_POST",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="rewardactions",
            name="action",
            field=models.CharField(
                choices=[
                    ("COMMENTS", "COMMENTS"),
                    ("LIKE", "LIKE"),
                    ("FOLLOW", "FOLLOW"),
                    ("SAVE", "SAVE"),
                    ("SHARE", "SHARE"),
                ],
                default="COMMENTS",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="rewardrequests",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=ezziee.utils.files.FileUploader.profile_image_upload_path,
                validators=[ezziee.utils.validators.image_validate_file_extension],
            ),
        ),
    ]
