# Generated by Django 4.2.8 on 2023-12-25 08:39

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("monetize", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbankaccount",
            name="account_name",
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
