# Generated by Django 4.2.8 on 2023-12-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("monetize", "0002_alter_userbankaccount_account_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbankaccount",
            name="bank",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="monetize.banks",
            ),
        ),
        migrations.AlterField(
            model_name="userbankaccount",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
