# Generated by Django 4.2.8 on 2023-12-15 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
import ezziee.utils.files
import ezziee.utils.validators
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "lcode",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
                ("country_iso", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Bank",
                "verbose_name_plural": "Banks",
                "ordering": ["name", "country_iso"],
            },
        ),
        migrations.CreateModel(
            name="RewardRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.FileField(
                        upload_to=ezziee.utils.files.FileUploader.profile_image_upload_path,
                        validators=[
                            ezziee.utils.validators.image_validate_file_extension
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("description", models.TextField()),
                ("expiry", models.DateField(blank=True, null=True)),
                ("fb_share_url", models.CharField(blank=True, max_length=500)),
                ("fb_like_url", models.CharField(blank=True, max_length=500)),
                ("fb_comment_url", models.CharField(blank=True, max_length=500)),
                ("fb_follow_url", models.CharField(blank=True, max_length=500)),
                ("fb_post_id", models.CharField(blank=True, max_length=500)),
                ("ig_share_url", models.CharField(blank=True, max_length=500)),
                ("ig_like_url", models.CharField(blank=True, max_length=500)),
                ("ig_comment_url", models.CharField(blank=True, max_length=500)),
                ("ig_follow_url", models.CharField(blank=True, max_length=500)),
                ("ig_post_id", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="facebook_id",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Facebook User ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="facebook_token",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Facebook Graph Token"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Phone Number"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="soundcloud_token",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Soundcloud Token"
            ),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "ordering": ["user__id"],
            },
        ),
        migrations.CreateModel(
            name="UserBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("verified", models.BooleanField(default=True)),
                (
                    "account_number",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=20, null=True
                    ),
                ),
                (
                    "routing_number",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=20, null=True
                    ),
                ),
                (
                    "account_name",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=20, null=True
                    ),
                ),
                (
                    "sort_code",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=20, null=True
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="users.banks",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Bank Account",
                "verbose_name_plural": "Users Bank Accounts",
                "ordering": ["-modified"],
            },
        ),
        migrations.CreateModel(
            name="RewardActions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("COMMENTS", "COMMENTS"),
                            ("LIKES", "LIKES"),
                            ("FOLLOWING", "FOLLOWING"),
                            ("SHARE", "SHARE"),
                        ],
                        default="COMMENTS",
                        max_length=25,
                    ),
                ),
                (
                    "reward_amount",
                    models.DecimalField(decimal_places=2, default=0.05, max_digits=20),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("FACEBOOK", "FACEBOOK"), ("INSTAGRAM", "INSTAGRAM")],
                        default="FACEBOOK",
                        max_length=25,
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="users.rewardrequests",
                    ),
                ),
                (
                    "subscribers",
                    models.ManyToManyField(
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="subscribers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward Action",
                "verbose_name_plural": "Rewards Actions",
                "ordering": ["-modified"],
            },
        ),
    ]
