# Generated by Django 4.2.8 on 2023-12-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_banks_rewardrequests_user_facebook_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rewardactions",
            name="reward",
        ),
        migrations.RemoveField(
            model_name="rewardactions",
            name="subscribers",
        ),
        migrations.RemoveField(
            model_name="userbankaccount",
            name="bank",
        ),
        migrations.RemoveField(
            model_name="userbankaccount",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="soundcloud_token",
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Instagram User ID"),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_access_token",
            field=models.CharField(blank=True, max_length=500, verbose_name="Spotify User Access Token"),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_code",
            field=models.CharField(blank=True, max_length=500, verbose_name="Spotify User Auth Code"),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Spotify User ID"),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_refresh_token",
            field=models.CharField(blank=True, max_length=500, verbose_name="Spotify User Refresh Token"),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube_access_token",
            field=models.CharField(blank=True, max_length=500, verbose_name="Spotify User Access Token"),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube_code",
            field=models.CharField(blank=True, max_length=500, verbose_name="Spotify User Auth Code"),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Spotify User ID"),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube_refresh_token",
            field=models.CharField(blank=True, max_length=500, verbose_name="Spotify User Refresh Token"),
        ),
        migrations.DeleteModel(
            name="Banks",
        ),
        migrations.DeleteModel(
            name="RewardActions",
        ),
        migrations.DeleteModel(
            name="RewardRequests",
        ),
        migrations.DeleteModel(
            name="UserBankAccount",
        ),
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
